server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
    include-path: never
    include-code: never
    include-timestamp: always
    include-binding-errors-field: false
logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect