server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
    include-path: never
    include-code: never
    include-timestamp: always
    include-binding-errors-field: false
logging:
  level:
    org:
      springframework:
        security: INFO
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dbuser}
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:dbpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
liquibase:
  enabled: true
  change-log: classpath:/changelog/changelog-master.yaml